### ISSUE TITLE
Navigating to `/` shows "Welcome to nginx!"

### ISSUE THREAD

**Issue by ght** [kantord/me#2]
(Not really an issue here, but this was the best way I found to bring this to your attention)

## Steps to Reproduce
Navigate to https://www.daniel-kantor.com from your CV by manually editing the URL

## Observed Behavior
The default "Welcome to nginx!" page is displayed

## Expected Behavior
Either a homepage, or a redirect to the CV

---
You probably already know this and plan to put something there soon, but since the last commit to this repo was a while back, I thought maybe you forgot to change the config to at least redirect until you have more content instead of showing the placeholder page :)

Thank you for LibreLingo, looks really promising!

**Comment by kantord** [comment]
thanks, I "fixed" it, now it has just a link to the cv :smile:  https://daniel-kantor.com/
